# cargo-audit configuration
# See: https://docs.rs/cargo-audit/latest/cargo_audit/

[advisories]
# Ignore advisories for the given crate IDs
ignore = []

# Ignore advisories for the given advisory IDs
ignore-yanked = false

# Path to the advisory database (will be cloned if it doesn't exist)
database-path = ".cargo/advisory-db"

# URL to the advisory database repository
database-url = "https://github.com/RustSec/advisory-db.git"

# Target platforms to check against
targets = []

# Check for informational advisories in addition to vulnerabilities
informational_warnings = ["unmaintained", "unsound", "yanked"]

# Deny specific categories of informational advisories
# Possible values: "notice", "informational", "unsound", "unmaintained", "yanked"
deny_warnings = []

# Only check for yanked crates (useful for CI where you want to fail fast)
yanked_only = false

# Threshold for vulnerability scores using CVSS metrics
# vulnerability_threshold = 0.0

[output]
# Output format: json, toml, or human-readable
format = "human"

# Disable colored output
no_color = false

# Don't print the banner
quiet = false
