//! OData filter field definitions for Language resources.

use modkit_odata_macros::ODataFilterable;
use time::OffsetDateTime;
use uuid::Uuid;

/// Language filterable fields schema.
///
/// This struct defines which fields can be used in OData $filter queries
/// for language resources. The field names match the wire format.
#[derive(ODataFilterable)]
pub struct LanguageQuery {
    #[odata(filter(kind = "Uuid"))]
    pub id: Uuid,

    #[odata(filter(kind = "String"))]
    pub code: String,

    #[odata(filter(kind = "String"))]
    pub name: String,

    #[odata(filter(kind = "DateTimeUtc"))]
    pub created_at: OffsetDateTime,
}

/// Type alias for the generated filter field enum.
///
/// This enum is auto-generated by the `ODataFilterable` derive macro
/// and represents all filterable fields for languages.
pub use LanguageQueryFilterField as LanguageFilterField;
