//! `OData` filter field definitions for Language resources.

use modkit_odata_macros::ODataFilterable;
use modkit_sdk::odata::{FieldRef, Schema};
use time::OffsetDateTime;
use uuid::Uuid;

use modkit_odata::filter::FilterField as _;

/// Language filterable fields schema.
///
/// This struct defines which fields can be used in `OData` $filter queries
/// for language resources. The field names match the wire format.
#[derive(ODataFilterable)]
pub struct LanguageQuery {
    #[odata(filter(kind = "Uuid"))]
    pub id: Uuid,

    #[odata(filter(kind = "String"))]
    pub code: String,

    #[odata(filter(kind = "String"))]
    pub name: String,

    #[odata(filter(kind = "DateTimeUtc"))]
    pub created_at: OffsetDateTime,
}

/// Type alias for the generated filter field enum.
///
/// This enum is auto-generated by the `ODataFilterable` derive macro
/// and represents all filterable fields for languages.
pub use LanguageQueryFilterField as LanguageFilterField;

#[derive(Debug, Clone, Copy)]
pub struct LanguageSchema;

impl Schema for LanguageSchema {
    type Field = LanguageFilterField;

    fn field_name(field: Self::Field) -> &'static str {
        field.name()
    }
}

pub const LANGUAGE_ID: FieldRef<LanguageSchema, Uuid> = FieldRef::new(LanguageFilterField::Id);
pub const LANGUAGE_CODE: FieldRef<LanguageSchema, String> =
    FieldRef::new(LanguageFilterField::Code);
pub const LANGUAGE_NAME: FieldRef<LanguageSchema, String> =
    FieldRef::new(LanguageFilterField::Name);
pub const LANGUAGE_CREATED_AT: FieldRef<LanguageSchema, OffsetDateTime> =
    FieldRef::new(LanguageFilterField::CreatedAt);
