//! OData filter field definitions for User resources.

use modkit_odata_macros::ODataFilterable;
use time::OffsetDateTime;
use uuid::Uuid;

/// User filterable fields schema.
///
/// This struct defines which fields can be used in OData $filter queries
/// for user resources. The field names match the wire format.
#[derive(ODataFilterable)]
pub struct UserQuery {
    #[odata(filter(kind = "Uuid"))]
    pub id: Uuid,

    #[odata(filter(kind = "String"))]
    pub email: String,

    #[odata(filter(kind = "DateTimeUtc"))]
    pub created_at: OffsetDateTime,
}

/// Type alias for the generated filter field enum.
///
/// This enum is auto-generated by the `ODataFilterable` derive macro
/// and represents all filterable fields for users.
pub use UserQueryFilterField as UserFilterField;
