# HyperSpot Server Configuration
# Updated to use the new configuration structure

# Core server configuration (global section)  
server:
  home_dir: "~/.hyperspot"

# Logging configuration (global section)
logging:
  default:
    console_level: info
    file: "logs/hyperspot.log"
    file_level: warn
    max_age_days: 28
    max_backups: 3
    max_size_mb: 1000

# Per-module configurations using new structure
modules:
  api_ingress:
    # No database configuration needed for api_ingress
    config:
      bind_addr: "127.0.0.1:8087"
      enable_docs: true
      cors_enabled: true
