# HyperSpot Server Configuration

# Core server configuration (global section)  
server:
  home_dir: "~/.hyperspot"

# Database configuration (simplified structure)
database:
  servers:
    # SQLite server for users_info module (no filename - modules specify their own files)
    sqlite_users:
      params:
        WAL: "true"
        synchronous: "NORMAL"
        busy_timeout: "5000"
      pool:
        max_conns: 5
        acquire_timeout: "30s"

# Logging configuration (global section)
logging:
  # global section
  default:
    console_level: info
    file: "logs/hyperspot.log"
    file_level: info
    max_age_days: 28
    max_backups: 3
    max_size_mb: 1000
  # api_ingress section
  api_ingress:
    console_level: info
    file: "logs/api.log"
    file_level: info
    max_age_days: 28
    max_backups: 3
    max_size_mb: 10000


# Per-module configurations using new structure
modules:
  api_ingress:
    # No database needed for api_ingress
    config:
      bind_addr: "127.0.0.1:8088"
      enable_docs: true
      cors_enabled: false
  
  users_info:
    # SQLite database for user information
    database:
      server: "sqlite_users"
      file: "users_info.db"  # Will be placed in ~/.hyperspot/users_info/users_info.db
    config:
      default_page_size: 5
      max_page_size: 100

