default: true

# Allow arbitrary line length
# Reason: One-sentence-per-line rule. Sentences may exceed 80 chars with links.
MD013: false

# Allow duplicate headings
# Reason: Option titles often repeat as ADR titles; "Examples" used multiple times.
MD024: false

# Allow multiple consecutive blank lines
# Reason: Templates use blank lines as placeholders for content.
MD012: false

# Allow bare URLs
# Reason: Common in ADRs for quick references to external resources.
MD034: false

# Disable table column spacing rule
# Reason: Markdown tables are readable without strict spacing.
MD060: false
